rehash;

if isempty(file_search('blb_anl_rp\w+',folder))
    blb_file_txt = fullfile(folder,['blb_anl_' exp_name '.txt']);
    blb_file_xlsx = fullfile(folder,['blb_anl_labels_' exp_name '.xlsx']);
    
if strcmpi(BoundaryChannel,Achannel)
    files = ['bsa_' prefix exp_name '\w+' Achannel '.TIF'];
elseif strcmpi(BoundaryChannel,FRETchannel)
    files = ['c_' prefix exp_name '\w+' FRETchannel '.TIF'];
elseif strcmpi(BoundaryChannel,Dchannel)
    files = ['bsd_' prefix exp_name '\w+' Dchannel '.TIF'];
end    
    newcols = boundary_dist(blb_file_txt,files,folder);
    
    % Save text version
    d = load(blb_file_txt);
    d = horzcat(d,newcols);
    save(fullfile(folder,['blb_anl_rp_' exp_name '.txt']),'d','-ascii')
    
    % Save version with headers
    d1 = importdata(blb_file_xlsx);
    headers = horzcat(d1.colheaders,{...
        'Cell ID'...
        'FA Distance from Cell Edge'...
        'FA Distance from Cell Centroid'...
        'Cell Area'...
        'Cell Convex Area'...
        'Cell Perimeter'...
        'Cell Major Axis Length'...
        'Cell Minor Axis Length'...
        'Cell Axis Ratio'...
        'Cell Orientation'...
        'Cell Centroid X'...
        'Cell Centroid Y'});
    d = num2cell(d);
    d = vertcat(headers,d);
    xlswrite(fullfile(folder,['blb_anl_rp_labels_' exp_name '.xlsx']),d)
end